### ISSUE TITLE
Error on 'eval "$(aliases init --global)"'

### ISSUE THREAD

**Issue by unforswearing** [sebglazebrook/aliases#4]
Hello, 

I have been using aliases for a few weeks now, but recently noticed an error when I reload my shell: 
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: MissingFieldError("users")', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
When attempting to use `aliases` in my project directory I receive the same error as above, and any aliases set with the `.alias` file returns the error `-bash: archive: command not found`

Here is my alias file for reference: 

```
archive:
  command: . archive-project.sh
  backout_seconds: 3
new:
  command: . new-project.sh
  backout_seconds: 3

```

And I am on OSX 10.10.5

Please let me know if you need any additional information from me. Thanks!
