### ISSUE TITLE
Nested aliases or reference to other alias.

### ISSUE THREAD

**Issue by wesselvdv** [sebglazebrook/aliases#53]
Currently to achieve nested aliases we have to embed entire case switch statement inside the .aliases file that pick up the aliasing parts. Might be awesome to be able to create nested aliases? Would allow us to create very advanced aliases.

**Comment by sebglazebrook** [comment]
I'm not sure I follow.

You can do nested aliases pretty easily. An example `.aliases` file would be:

```yaml
dc:
  command: docker-compose
up:
  command: dc up
```

Does that cover what you mean?
